# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created: Fri Nov 14 17:11:14 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 630)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 630))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.dataTab = QtGui.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.dataTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.dataTab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.statsPaste = QtGui.QTextEdit(self.dataTab)
        self.statsPaste.setAcceptRichText(False)
        self.statsPaste.setObjectName("statsPaste")
        self.verticalLayout.addWidget(self.statsPaste)
        self.phraseButton = QtGui.QPushButton(self.dataTab)
        self.phraseButton.setObjectName("phraseButton")
        self.verticalLayout.addWidget(self.phraseButton)
        self.tabWidget.addTab(self.dataTab, "")
        self.filtersTab = QtGui.QWidget()
        self.filtersTab.setObjectName("filtersTab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.filtersTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtGui.QFrame(self.filtersTab)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formatFrame = QtGui.QFrame(self.frame)
        self.formatFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.formatFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.formatFrame.setObjectName("formatFrame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.formatFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formatLabel = QtGui.QLabel(self.formatFrame)
        self.formatLabel.setObjectName("formatLabel")
        self.verticalLayout_2.addWidget(self.formatLabel)
        self.standardFilter = QtGui.QCheckBox(self.formatFrame)
        self.standardFilter.setChecked(True)
        self.standardFilter.setObjectName("standardFilter")
        self.verticalLayout_2.addWidget(self.standardFilter)
        self.modernFilter = QtGui.QCheckBox(self.formatFrame)
        self.modernFilter.setChecked(True)
        self.modernFilter.setObjectName("modernFilter")
        self.verticalLayout_2.addWidget(self.modernFilter)
        self.legacyFilter = QtGui.QCheckBox(self.formatFrame)
        self.legacyFilter.setChecked(True)
        self.legacyFilter.setObjectName("legacyFilter")
        self.verticalLayout_2.addWidget(self.legacyFilter)
        self.vintageFilter = QtGui.QCheckBox(self.formatFrame)
        self.vintageFilter.setChecked(True)
        self.vintageFilter.setObjectName("vintageFilter")
        self.verticalLayout_2.addWidget(self.vintageFilter)
        self.boosterDraftFilter = QtGui.QCheckBox(self.formatFrame)
        self.boosterDraftFilter.setChecked(True)
        self.boosterDraftFilter.setObjectName("boosterDraftFilter")
        self.verticalLayout_2.addWidget(self.boosterDraftFilter)
        self.sealedFilter = QtGui.QCheckBox(self.formatFrame)
        self.sealedFilter.setChecked(True)
        self.sealedFilter.setObjectName("sealedFilter")
        self.verticalLayout_2.addWidget(self.sealedFilter)
        self.twoHGSealedFilter = QtGui.QCheckBox(self.formatFrame)
        self.twoHGSealedFilter.setChecked(True)
        self.twoHGSealedFilter.setObjectName("twoHGSealedFilter")
        self.verticalLayout_2.addWidget(self.twoHGSealedFilter)
        self.casualConFilter = QtGui.QCheckBox(self.formatFrame)
        self.casualConFilter.setChecked(True)
        self.casualConFilter.setObjectName("casualConFilter")
        self.verticalLayout_2.addWidget(self.casualConFilter)
        self.casualLimFilter = QtGui.QCheckBox(self.formatFrame)
        self.casualLimFilter.setChecked(True)
        self.casualLimFilter.setObjectName("casualLimFilter")
        self.verticalLayout_2.addWidget(self.casualLimFilter)
        self.otherFormatFilter = QtGui.QCheckBox(self.formatFrame)
        self.otherFormatFilter.setChecked(True)
        self.otherFormatFilter.setObjectName("otherFormatFilter")
        self.verticalLayout_2.addWidget(self.otherFormatFilter)
        self.horizontalLayout_4.addWidget(self.formatFrame)
        self.eventFrame = QtGui.QFrame(self.frame)
        self.eventFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.eventFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.eventFrame.setObjectName("eventFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.eventFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.eventLabel = QtGui.QLabel(self.eventFrame)
        self.eventLabel.setObjectName("eventLabel")
        self.verticalLayout_3.addWidget(self.eventLabel)
        self.premiumTournamentFilter = QtGui.QCheckBox(self.eventFrame)
        self.premiumTournamentFilter.setChecked(True)
        self.premiumTournamentFilter.setObjectName("premiumTournamentFilter")
        self.verticalLayout_3.addWidget(self.premiumTournamentFilter)
        self.grandPrixFilter = QtGui.QCheckBox(self.eventFrame)
        self.grandPrixFilter.setChecked(True)
        self.grandPrixFilter.setObjectName("grandPrixFilter")
        self.verticalLayout_3.addWidget(self.grandPrixFilter)
        self.proTourFilter = QtGui.QCheckBox(self.eventFrame)
        self.proTourFilter.setChecked(True)
        self.proTourFilter.setObjectName("proTourFilter")
        self.verticalLayout_3.addWidget(self.proTourFilter)
        self.PTQFilter = QtGui.QCheckBox(self.eventFrame)
        self.PTQFilter.setChecked(True)
        self.PTQFilter.setObjectName("PTQFilter")
        self.verticalLayout_3.addWidget(self.PTQFilter)
        self.gameDayFilter = QtGui.QCheckBox(self.eventFrame)
        self.gameDayFilter.setChecked(True)
        self.gameDayFilter.setObjectName("gameDayFilter")
        self.verticalLayout_3.addWidget(self.gameDayFilter)
        self.prereleaseFilter = QtGui.QCheckBox(self.eventFrame)
        self.prereleaseFilter.setChecked(True)
        self.prereleaseFilter.setObjectName("prereleaseFilter")
        self.verticalLayout_3.addWidget(self.prereleaseFilter)
        self.GPTFilter = QtGui.QCheckBox(self.eventFrame)
        self.GPTFilter.setChecked(True)
        self.GPTFilter.setObjectName("GPTFilter")
        self.verticalLayout_3.addWidget(self.GPTFilter)
        self.FNMFilter = QtGui.QCheckBox(self.eventFrame)
        self.FNMFilter.setChecked(True)
        self.FNMFilter.setObjectName("FNMFilter")
        self.verticalLayout_3.addWidget(self.FNMFilter)
        self.WMCQFilter = QtGui.QCheckBox(self.eventFrame)
        self.WMCQFilter.setChecked(True)
        self.WMCQFilter.setObjectName("WMCQFilter")
        self.verticalLayout_3.addWidget(self.WMCQFilter)
        self.otherEventFilter = QtGui.QCheckBox(self.eventFrame)
        self.otherEventFilter.setChecked(True)
        self.otherEventFilter.setObjectName("otherEventFilter")
        self.verticalLayout_3.addWidget(self.otherEventFilter)
        self.horizontalLayout_4.addWidget(self.eventFrame)
        self.datesFrame = QtGui.QFrame(self.frame)
        self.datesFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.datesFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.datesFrame.setObjectName("datesFrame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.datesFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.datesLabel = QtGui.QLabel(self.datesFrame)
        self.datesLabel.setObjectName("datesLabel")
        self.verticalLayout_4.addWidget(self.datesLabel)
        self.startingDate = QtGui.QCalendarWidget(self.datesFrame)
        self.startingDate.setSelectedDate(QtCore.QDate(1991, 1, 1))
        self.startingDate.setMinimumDate(QtCore.QDate(1991, 1, 1))
        self.startingDate.setObjectName("startingDate")
        self.verticalLayout_4.addWidget(self.startingDate)
        self.label_2 = QtGui.QLabel(self.datesFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.endingDate = QtGui.QCalendarWidget(self.datesFrame)
        self.endingDate.setSelectedDate(QtCore.QDate(2015, 12, 31))
        self.endingDate.setMinimumDate(QtCore.QDate(1991, 1, 1))
        self.endingDate.setObjectName("endingDate")
        self.verticalLayout_4.addWidget(self.endingDate)
        self.horizontalLayout_4.addWidget(self.datesFrame)
        self.verticalLayout_5.addWidget(self.frame)
        self.updateFiltersButton = QtGui.QPushButton(self.filtersTab)
        self.updateFiltersButton.setObjectName("updateFiltersButton")
        self.verticalLayout_5.addWidget(self.updateFiltersButton)
        self.tabWidget.addTab(self.filtersTab, "")
        self.eventListTab = QtGui.QWidget()
        self.eventListTab.setObjectName("eventListTab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.eventListTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.eventTree = QtGui.QTreeWidget(self.eventListTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventTree.sizePolicy().hasHeightForWidth())
        self.eventTree.setSizePolicy(sizePolicy)
        self.eventTree.setAutoFillBackground(False)
        self.eventTree.setObjectName("eventTree")
        self.horizontalLayout_2.addWidget(self.eventTree)
        self.tabWidget.addTab(self.eventListTab, "")
        self.opponentTab = QtGui.QWidget()
        self.opponentTab.setObjectName("opponentTab")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.opponentTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.opponentTree = QtGui.QTreeWidget(self.opponentTab)
        self.opponentTree.setAutoFillBackground(False)
        self.opponentTree.setObjectName("opponentTree")
        self.horizontalLayout_3.addWidget(self.opponentTree)
        self.tabWidget.addTab(self.opponentTab, "")
        self.formatTab = QtGui.QWidget()
        self.formatTab.setObjectName("formatTab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.formatTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtGui.QScrollArea(self.formatTab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1420, 502))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.standardFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.standardFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.standardFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.standardFrame.setObjectName("standardFrame")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.standardFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtGui.QLabel(self.standardFrame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.standardRecord = QtGui.QLabel(self.standardFrame)
        self.standardRecord.setObjectName("standardRecord")
        self.verticalLayout_7.addWidget(self.standardRecord)
        self.standardMatches = QtGui.QLabel(self.standardFrame)
        self.standardMatches.setObjectName("standardMatches")
        self.verticalLayout_7.addWidget(self.standardMatches)
        self.standardWinPercent = QtGui.QLabel(self.standardFrame)
        self.standardWinPercent.setObjectName("standardWinPercent")
        self.verticalLayout_7.addWidget(self.standardWinPercent)
        self.horizontalLayout_5.addWidget(self.standardFrame)
        self.modernFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.modernFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.modernFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.modernFrame.setObjectName("modernFrame")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.modernFrame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtGui.QLabel(self.modernFrame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.modernRecord = QtGui.QLabel(self.modernFrame)
        self.modernRecord.setObjectName("modernRecord")
        self.verticalLayout_8.addWidget(self.modernRecord)
        self.modernMatches = QtGui.QLabel(self.modernFrame)
        self.modernMatches.setObjectName("modernMatches")
        self.verticalLayout_8.addWidget(self.modernMatches)
        self.modernWinPercent = QtGui.QLabel(self.modernFrame)
        self.modernWinPercent.setObjectName("modernWinPercent")
        self.verticalLayout_8.addWidget(self.modernWinPercent)
        self.horizontalLayout_5.addWidget(self.modernFrame)
        self.legacyFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.legacyFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.legacyFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.legacyFrame.setObjectName("legacyFrame")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.legacyFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtGui.QLabel(self.legacyFrame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.legacyRecord = QtGui.QLabel(self.legacyFrame)
        self.legacyRecord.setObjectName("legacyRecord")
        self.verticalLayout_9.addWidget(self.legacyRecord)
        self.legacyMatches = QtGui.QLabel(self.legacyFrame)
        self.legacyMatches.setObjectName("legacyMatches")
        self.verticalLayout_9.addWidget(self.legacyMatches)
        self.legacyWinPercent = QtGui.QLabel(self.legacyFrame)
        self.legacyWinPercent.setObjectName("legacyWinPercent")
        self.verticalLayout_9.addWidget(self.legacyWinPercent)
        self.horizontalLayout_5.addWidget(self.legacyFrame)
        self.vintageFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.vintageFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.vintageFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.vintageFrame.setObjectName("vintageFrame")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.vintageFrame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_23 = QtGui.QLabel(self.vintageFrame)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        self.vintageRecord = QtGui.QLabel(self.vintageFrame)
        self.vintageRecord.setObjectName("vintageRecord")
        self.verticalLayout_12.addWidget(self.vintageRecord)
        self.vintageMatches = QtGui.QLabel(self.vintageFrame)
        self.vintageMatches.setObjectName("vintageMatches")
        self.verticalLayout_12.addWidget(self.vintageMatches)
        self.vintageWinPercent = QtGui.QLabel(self.vintageFrame)
        self.vintageWinPercent.setObjectName("vintageWinPercent")
        self.verticalLayout_12.addWidget(self.vintageWinPercent)
        self.horizontalLayout_5.addWidget(self.vintageFrame)
        self.draftFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.draftFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.draftFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.draftFrame.setObjectName("draftFrame")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.draftFrame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtGui.QLabel(self.draftFrame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.draftRecord = QtGui.QLabel(self.draftFrame)
        self.draftRecord.setObjectName("draftRecord")
        self.verticalLayout_11.addWidget(self.draftRecord)
        self.draftMatches = QtGui.QLabel(self.draftFrame)
        self.draftMatches.setObjectName("draftMatches")
        self.verticalLayout_11.addWidget(self.draftMatches)
        self.draftWinPercent = QtGui.QLabel(self.draftFrame)
        self.draftWinPercent.setObjectName("draftWinPercent")
        self.verticalLayout_11.addWidget(self.draftWinPercent)
        self.horizontalLayout_5.addWidget(self.draftFrame)
        self.sealedFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.sealedFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sealedFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sealedFrame.setObjectName("sealedFrame")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.sealedFrame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_6 = QtGui.QLabel(self.sealedFrame)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.sealedRecord = QtGui.QLabel(self.sealedFrame)
        self.sealedRecord.setObjectName("sealedRecord")
        self.verticalLayout_10.addWidget(self.sealedRecord)
        self.sealedMatches = QtGui.QLabel(self.sealedFrame)
        self.sealedMatches.setObjectName("sealedMatches")
        self.verticalLayout_10.addWidget(self.sealedMatches)
        self.sealedWinPercent = QtGui.QLabel(self.sealedFrame)
        self.sealedWinPercent.setObjectName("sealedWinPercent")
        self.verticalLayout_10.addWidget(self.sealedWinPercent)
        self.horizontalLayout_5.addWidget(self.sealedFrame)
        self.twoHGFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.twoHGFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.twoHGFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.twoHGFrame.setObjectName("twoHGFrame")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.twoHGFrame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_27 = QtGui.QLabel(self.twoHGFrame)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_13.addWidget(self.label_27)
        self.twoHGRecord = QtGui.QLabel(self.twoHGFrame)
        self.twoHGRecord.setObjectName("twoHGRecord")
        self.verticalLayout_13.addWidget(self.twoHGRecord)
        self.twoHGMatches = QtGui.QLabel(self.twoHGFrame)
        self.twoHGMatches.setObjectName("twoHGMatches")
        self.verticalLayout_13.addWidget(self.twoHGMatches)
        self.twoHGWinPercent = QtGui.QLabel(self.twoHGFrame)
        self.twoHGWinPercent.setObjectName("twoHGWinPercent")
        self.verticalLayout_13.addWidget(self.twoHGWinPercent)
        self.horizontalLayout_5.addWidget(self.twoHGFrame)
        self.casualConFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.casualConFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.casualConFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.casualConFrame.setObjectName("casualConFrame")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.casualConFrame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_31 = QtGui.QLabel(self.casualConFrame)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_14.addWidget(self.label_31)
        self.casualConRecord = QtGui.QLabel(self.casualConFrame)
        self.casualConRecord.setObjectName("casualConRecord")
        self.verticalLayout_14.addWidget(self.casualConRecord)
        self.casualConMatches = QtGui.QLabel(self.casualConFrame)
        self.casualConMatches.setObjectName("casualConMatches")
        self.verticalLayout_14.addWidget(self.casualConMatches)
        self.casualConWinPercent = QtGui.QLabel(self.casualConFrame)
        self.casualConWinPercent.setObjectName("casualConWinPercent")
        self.verticalLayout_14.addWidget(self.casualConWinPercent)
        self.horizontalLayout_5.addWidget(self.casualConFrame)
        self.casualLimFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.casualLimFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.casualLimFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.casualLimFrame.setObjectName("casualLimFrame")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.casualLimFrame)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_39 = QtGui.QLabel(self.casualLimFrame)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_16.addWidget(self.label_39)
        self.casualLimRecord = QtGui.QLabel(self.casualLimFrame)
        self.casualLimRecord.setObjectName("casualLimRecord")
        self.verticalLayout_16.addWidget(self.casualLimRecord)
        self.casualLimMatches = QtGui.QLabel(self.casualLimFrame)
        self.casualLimMatches.setObjectName("casualLimMatches")
        self.verticalLayout_16.addWidget(self.casualLimMatches)
        self.casualLimWinPercent = QtGui.QLabel(self.casualLimFrame)
        self.casualLimWinPercent.setObjectName("casualLimWinPercent")
        self.verticalLayout_16.addWidget(self.casualLimWinPercent)
        self.horizontalLayout_5.addWidget(self.casualLimFrame)
        self.otherFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.otherFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.otherFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.otherFrame.setObjectName("otherFrame")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.otherFrame)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_35 = QtGui.QLabel(self.otherFrame)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_15.addWidget(self.label_35)
        self.otherRecord = QtGui.QLabel(self.otherFrame)
        self.otherRecord.setObjectName("otherRecord")
        self.verticalLayout_15.addWidget(self.otherRecord)
        self.otherMatches = QtGui.QLabel(self.otherFrame)
        self.otherMatches.setObjectName("otherMatches")
        self.verticalLayout_15.addWidget(self.otherMatches)
        self.otherWinPercent = QtGui.QLabel(self.otherFrame)
        self.otherWinPercent.setObjectName("otherWinPercent")
        self.verticalLayout_15.addWidget(self.otherWinPercent)
        self.horizontalLayout_5.addWidget(self.otherFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.exportStats = QtGui.QPushButton(self.formatTab)
        self.exportStats.setObjectName("exportStats")
        self.verticalLayout_6.addWidget(self.exportStats)
        self.tabWidget.addTab(self.formatTab, "")
        self.eventTab = QtGui.QWidget()
        self.eventTab.setObjectName("eventTab")
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.eventTab)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.scrollArea_2 = QtGui.QScrollArea(self.eventTab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1422, 502))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.proTourFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.proTourFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.proTourFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.proTourFrame.setObjectName("proTourFrame")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.proTourFrame)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_24 = QtGui.QLabel(self.proTourFrame)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_20.addWidget(self.label_24)
        self.proTourRecord = QtGui.QLabel(self.proTourFrame)
        self.proTourRecord.setObjectName("proTourRecord")
        self.verticalLayout_20.addWidget(self.proTourRecord)
        self.proTourMatches = QtGui.QLabel(self.proTourFrame)
        self.proTourMatches.setObjectName("proTourMatches")
        self.verticalLayout_20.addWidget(self.proTourMatches)
        self.proTourWinPercent = QtGui.QLabel(self.proTourFrame)
        self.proTourWinPercent.setObjectName("proTourWinPercent")
        self.verticalLayout_20.addWidget(self.proTourWinPercent)
        self.horizontalLayout_6.addWidget(self.proTourFrame)
        self.grandPrixFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.grandPrixFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.grandPrixFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.grandPrixFrame.setObjectName("grandPrixFrame")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.grandPrixFrame)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_8 = QtGui.QLabel(self.grandPrixFrame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_17.addWidget(self.label_8)
        self.grandPrixRecord = QtGui.QLabel(self.grandPrixFrame)
        self.grandPrixRecord.setObjectName("grandPrixRecord")
        self.verticalLayout_17.addWidget(self.grandPrixRecord)
        self.grandPrixMatches = QtGui.QLabel(self.grandPrixFrame)
        self.grandPrixMatches.setObjectName("grandPrixMatches")
        self.verticalLayout_17.addWidget(self.grandPrixMatches)
        self.grandPrixWinPercent = QtGui.QLabel(self.grandPrixFrame)
        self.grandPrixWinPercent.setObjectName("grandPrixWinPercent")
        self.verticalLayout_17.addWidget(self.grandPrixWinPercent)
        self.horizontalLayout_6.addWidget(self.grandPrixFrame)
        self.premiumFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.premiumFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.premiumFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.premiumFrame.setObjectName("premiumFrame")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.premiumFrame)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_9 = QtGui.QLabel(self.premiumFrame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_18.addWidget(self.label_9)
        self.premiumRecord = QtGui.QLabel(self.premiumFrame)
        self.premiumRecord.setObjectName("premiumRecord")
        self.verticalLayout_18.addWidget(self.premiumRecord)
        self.premiumMatches = QtGui.QLabel(self.premiumFrame)
        self.premiumMatches.setObjectName("premiumMatches")
        self.verticalLayout_18.addWidget(self.premiumMatches)
        self.premiumWinPercent = QtGui.QLabel(self.premiumFrame)
        self.premiumWinPercent.setObjectName("premiumWinPercent")
        self.verticalLayout_18.addWidget(self.premiumWinPercent)
        self.horizontalLayout_6.addWidget(self.premiumFrame)
        self.ptqFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.ptqFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ptqFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.ptqFrame.setObjectName("ptqFrame")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.ptqFrame)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_10 = QtGui.QLabel(self.ptqFrame)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_19.addWidget(self.label_10)
        self.ptqRecord = QtGui.QLabel(self.ptqFrame)
        self.ptqRecord.setObjectName("ptqRecord")
        self.verticalLayout_19.addWidget(self.ptqRecord)
        self.ptqMatches = QtGui.QLabel(self.ptqFrame)
        self.ptqMatches.setObjectName("ptqMatches")
        self.verticalLayout_19.addWidget(self.ptqMatches)
        self.ptqWinPercent = QtGui.QLabel(self.ptqFrame)
        self.ptqWinPercent.setObjectName("ptqWinPercent")
        self.verticalLayout_19.addWidget(self.ptqWinPercent)
        self.horizontalLayout_6.addWidget(self.ptqFrame)
        self.wmcqFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.wmcqFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.wmcqFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.wmcqFrame.setObjectName("wmcqFrame")
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.wmcqFrame)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_32 = QtGui.QLabel(self.wmcqFrame)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_24.addWidget(self.label_32)
        self.wmcqRecord = QtGui.QLabel(self.wmcqFrame)
        self.wmcqRecord.setObjectName("wmcqRecord")
        self.verticalLayout_24.addWidget(self.wmcqRecord)
        self.wmcqMatches = QtGui.QLabel(self.wmcqFrame)
        self.wmcqMatches.setObjectName("wmcqMatches")
        self.verticalLayout_24.addWidget(self.wmcqMatches)
        self.wmcqWinPercent = QtGui.QLabel(self.wmcqFrame)
        self.wmcqWinPercent.setObjectName("wmcqWinPercent")
        self.verticalLayout_24.addWidget(self.wmcqWinPercent)
        self.horizontalLayout_6.addWidget(self.wmcqFrame)
        self.gptFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.gptFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gptFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.gptFrame.setObjectName("gptFrame")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.gptFrame)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_12 = QtGui.QLabel(self.gptFrame)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_22.addWidget(self.label_12)
        self.gptRecord = QtGui.QLabel(self.gptFrame)
        self.gptRecord.setObjectName("gptRecord")
        self.verticalLayout_22.addWidget(self.gptRecord)
        self.gptMatches = QtGui.QLabel(self.gptFrame)
        self.gptMatches.setObjectName("gptMatches")
        self.verticalLayout_22.addWidget(self.gptMatches)
        self.gptWinPercent = QtGui.QLabel(self.gptFrame)
        self.gptWinPercent.setObjectName("gptWinPercent")
        self.verticalLayout_22.addWidget(self.gptWinPercent)
        self.horizontalLayout_6.addWidget(self.gptFrame)
        self.fnmFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.fnmFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fnmFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fnmFrame.setObjectName("fnmFrame")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.fnmFrame)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_11 = QtGui.QLabel(self.fnmFrame)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_21.addWidget(self.label_11)
        self.fnmRecord = QtGui.QLabel(self.fnmFrame)
        self.fnmRecord.setObjectName("fnmRecord")
        self.verticalLayout_21.addWidget(self.fnmRecord)
        self.fnmMatches = QtGui.QLabel(self.fnmFrame)
        self.fnmMatches.setObjectName("fnmMatches")
        self.verticalLayout_21.addWidget(self.fnmMatches)
        self.fnmWinPercent = QtGui.QLabel(self.fnmFrame)
        self.fnmWinPercent.setObjectName("fnmWinPercent")
        self.verticalLayout_21.addWidget(self.fnmWinPercent)
        self.horizontalLayout_6.addWidget(self.fnmFrame)
        self.prereleaseFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.prereleaseFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prereleaseFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.prereleaseFrame.setObjectName("prereleaseFrame")
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.prereleaseFrame)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_28 = QtGui.QLabel(self.prereleaseFrame)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_23.addWidget(self.label_28)
        self.prereleaseRecord = QtGui.QLabel(self.prereleaseFrame)
        self.prereleaseRecord.setObjectName("prereleaseRecord")
        self.verticalLayout_23.addWidget(self.prereleaseRecord)
        self.prereleaseMatches = QtGui.QLabel(self.prereleaseFrame)
        self.prereleaseMatches.setObjectName("prereleaseMatches")
        self.verticalLayout_23.addWidget(self.prereleaseMatches)
        self.prereleaseWinPercent = QtGui.QLabel(self.prereleaseFrame)
        self.prereleaseWinPercent.setObjectName("prereleaseWinPercent")
        self.verticalLayout_23.addWidget(self.prereleaseWinPercent)
        self.horizontalLayout_6.addWidget(self.prereleaseFrame)
        self.gameDayFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.gameDayFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gameDayFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.gameDayFrame.setObjectName("gameDayFrame")
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.gameDayFrame)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_40 = QtGui.QLabel(self.gameDayFrame)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_25.addWidget(self.label_40)
        self.gameDayRecord = QtGui.QLabel(self.gameDayFrame)
        self.gameDayRecord.setObjectName("gameDayRecord")
        self.verticalLayout_25.addWidget(self.gameDayRecord)
        self.gameDayMatches = QtGui.QLabel(self.gameDayFrame)
        self.gameDayMatches.setObjectName("gameDayMatches")
        self.verticalLayout_25.addWidget(self.gameDayMatches)
        self.gameDayWinPercent = QtGui.QLabel(self.gameDayFrame)
        self.gameDayWinPercent.setObjectName("gameDayWinPercent")
        self.verticalLayout_25.addWidget(self.gameDayWinPercent)
        self.horizontalLayout_6.addWidget(self.gameDayFrame)
        self.otherEventFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.otherEventFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.otherEventFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.otherEventFrame.setObjectName("otherEventFrame")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.otherEventFrame)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_36 = QtGui.QLabel(self.otherEventFrame)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_26.addWidget(self.label_36)
        self.otherEventRecord = QtGui.QLabel(self.otherEventFrame)
        self.otherEventRecord.setObjectName("otherEventRecord")
        self.verticalLayout_26.addWidget(self.otherEventRecord)
        self.otherEventMatches = QtGui.QLabel(self.otherEventFrame)
        self.otherEventMatches.setObjectName("otherEventMatches")
        self.verticalLayout_26.addWidget(self.otherEventMatches)
        self.otherEventWinPercent = QtGui.QLabel(self.otherEventFrame)
        self.otherEventWinPercent.setObjectName("otherEventWinPercent")
        self.verticalLayout_26.addWidget(self.otherEventWinPercent)
        self.horizontalLayout_6.addWidget(self.otherEventFrame)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_27.addWidget(self.scrollArea_2)
        self.exportStats_2 = QtGui.QPushButton(self.eventTab)
        self.exportStats_2.setObjectName("exportStats_2")
        self.verticalLayout_27.addWidget(self.exportStats_2)
        self.tabWidget.addTab(self.eventTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionMenu_Item = QtGui.QAction(MainWindow)
        self.actionMenu_Item.setObjectName("actionMenu_Item")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Qute MTG Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Paste Data Below:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.phraseButton.setText(QtGui.QApplication.translate("MainWindow", "Prase Data and Generate Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), QtGui.QApplication.translate("MainWindow", "Raw Data", None, QtGui.QApplication.UnicodeUTF8))
        self.formatLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Formats:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.standardFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.standardFilter.setText(QtGui.QApplication.translate("MainWindow", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.modernFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Modern", None, QtGui.QApplication.UnicodeUTF8))
        self.modernFilter.setText(QtGui.QApplication.translate("MainWindow", "Modern", None, QtGui.QApplication.UnicodeUTF8))
        self.legacyFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Legacy", None, QtGui.QApplication.UnicodeUTF8))
        self.legacyFilter.setText(QtGui.QApplication.translate("MainWindow", "Legacy", None, QtGui.QApplication.UnicodeUTF8))
        self.vintageFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Vintage", None, QtGui.QApplication.UnicodeUTF8))
        self.vintageFilter.setText(QtGui.QApplication.translate("MainWindow", "Vintage", None, QtGui.QApplication.UnicodeUTF8))
        self.boosterDraftFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Booster Draft", None, QtGui.QApplication.UnicodeUTF8))
        self.boosterDraftFilter.setText(QtGui.QApplication.translate("MainWindow", "Booster Draft", None, QtGui.QApplication.UnicodeUTF8))
        self.sealedFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Sealed", None, QtGui.QApplication.UnicodeUTF8))
        self.sealedFilter.setText(QtGui.QApplication.translate("MainWindow", "Sealed", None, QtGui.QApplication.UnicodeUTF8))
        self.twoHGSealedFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "2 HG Sealed", None, QtGui.QApplication.UnicodeUTF8))
        self.twoHGSealedFilter.setText(QtGui.QApplication.translate("MainWindow", "2 HG Sealed", None, QtGui.QApplication.UnicodeUTF8))
        self.casualConFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Casual - Constructed", None, QtGui.QApplication.UnicodeUTF8))
        self.casualConFilter.setText(QtGui.QApplication.translate("MainWindow", "Casual - Con", None, QtGui.QApplication.UnicodeUTF8))
        self.casualLimFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Casual - Limited", None, QtGui.QApplication.UnicodeUTF8))
        self.casualLimFilter.setText(QtGui.QApplication.translate("MainWindow", "Casual - Lim", None, QtGui.QApplication.UnicodeUTF8))
        self.otherFormatFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.otherFormatFilter.setText(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.eventLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Event Types:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.premiumTournamentFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Magic WPN Premium Tournament", None, QtGui.QApplication.UnicodeUTF8))
        self.premiumTournamentFilter.setText(QtGui.QApplication.translate("MainWindow", "Premium Tournament", None, QtGui.QApplication.UnicodeUTF8))
        self.grandPrixFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Magic Grand Prix", None, QtGui.QApplication.UnicodeUTF8))
        self.grandPrixFilter.setText(QtGui.QApplication.translate("MainWindow", "Grand Prix", None, QtGui.QApplication.UnicodeUTF8))
        self.proTourFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Magic Pro Tour", None, QtGui.QApplication.UnicodeUTF8))
        self.proTourFilter.setText(QtGui.QApplication.translate("MainWindow", "Pro Tour", None, QtGui.QApplication.UnicodeUTF8))
        self.PTQFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Magic Pro Tour Qualifier", None, QtGui.QApplication.UnicodeUTF8))
        self.PTQFilter.setText(QtGui.QApplication.translate("MainWindow", "Pro Tour Qualifier", None, QtGui.QApplication.UnicodeUTF8))
        self.gameDayFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Magic Game Day", None, QtGui.QApplication.UnicodeUTF8))
        self.gameDayFilter.setText(QtGui.QApplication.translate("MainWindow", "Game Day", None, QtGui.QApplication.UnicodeUTF8))
        self.prereleaseFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Magic Prerelease", None, QtGui.QApplication.UnicodeUTF8))
        self.prereleaseFilter.setText(QtGui.QApplication.translate("MainWindow", "Prerelease", None, QtGui.QApplication.UnicodeUTF8))
        self.GPTFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Magic Grand Prix Trial", None, QtGui.QApplication.UnicodeUTF8))
        self.GPTFilter.setText(QtGui.QApplication.translate("MainWindow", "Grand Prix Trial", None, QtGui.QApplication.UnicodeUTF8))
        self.FNMFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Friday Night Magic", None, QtGui.QApplication.UnicodeUTF8))
        self.FNMFilter.setText(QtGui.QApplication.translate("MainWindow", "Friday Night Magic", None, QtGui.QApplication.UnicodeUTF8))
        self.WMCQFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "World Magic Cup Qualifier", None, QtGui.QApplication.UnicodeUTF8))
        self.WMCQFilter.setText(QtGui.QApplication.translate("MainWindow", "WMCQ", None, QtGui.QApplication.UnicodeUTF8))
        self.otherEventFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.otherEventFilter.setText(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.datesLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Starting Date:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Ending Date:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.updateFiltersButton.setText(QtGui.QApplication.translate("MainWindow", "Apply Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.filtersTab), QtGui.QApplication.translate("MainWindow", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Place", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Players", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(6, QtGui.QApplication.translate("MainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(7, QtGui.QApplication.translate("MainWindow", "Wins", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(8, QtGui.QApplication.translate("MainWindow", "Losses", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(9, QtGui.QApplication.translate("MainWindow", "Draws", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(10, QtGui.QApplication.translate("MainWindow", "Opponents", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.eventListTab), QtGui.QApplication.translate("MainWindow", "Event List", None, QtGui.QApplication.UnicodeUTF8))
        self.opponentTree.setSortingEnabled(True)
        self.opponentTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Opponent", None, QtGui.QApplication.UnicodeUTF8))
        self.opponentTree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Wins", None, QtGui.QApplication.UnicodeUTF8))
        self.opponentTree.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Losses", None, QtGui.QApplication.UnicodeUTF8))
        self.opponentTree.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Draws", None, QtGui.QApplication.UnicodeUTF8))
        self.opponentTree.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.opponentTab), QtGui.QApplication.translate("MainWindow", "Opponent List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Standard:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.standardRecord.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Total Record</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.standardMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.standardWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Modern:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.modernRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.modernMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.modernWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Legacy:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.legacyRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.legacyMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.legacyWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Vintage:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.vintageRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.vintageMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.vintageWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Draft:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.draftRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.draftMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.draftWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Sealed:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.sealedRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.sealedMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.sealedWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">2 HG Sealed:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.twoHGRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.twoHGMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.twoHGWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Casual - Con:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.casualConRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.casualConMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.casualConWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Casual - Lim:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.casualLimRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.casualLimMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.casualLimWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Other:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.otherRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.otherMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.otherWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.exportStats.setText(QtGui.QApplication.translate("MainWindow", "Export Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.formatTab), QtGui.QApplication.translate("MainWindow", "Stats by Format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Pro Tour:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.proTourRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.proTourMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.proTourWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Grand Prix:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.grandPrixRecord.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Total Record</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.grandPrixMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.grandPrixWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Premium Event:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.premiumRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.premiumMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.premiumWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">PTQ:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ptqRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.ptqMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.ptqWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">WMCQ:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.wmcqRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.wmcqMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.wmcqWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">GPT:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.gptRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.gptMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.gptWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">FNM:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.fnmRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.fnmMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.fnmWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">PreRelease:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.prereleaseRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.prereleaseMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.prereleaseWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Game Day:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.gameDayRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.gameDayMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.gameDayWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Other:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.otherEventRecord.setText(QtGui.QApplication.translate("MainWindow", "Total Record", None, QtGui.QApplication.UnicodeUTF8))
        self.otherEventMatches.setText(QtGui.QApplication.translate("MainWindow", "Total Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.otherEventWinPercent.setText(QtGui.QApplication.translate("MainWindow", "Win %", None, QtGui.QApplication.UnicodeUTF8))
        self.exportStats_2.setText(QtGui.QApplication.translate("MainWindow", "Export Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.eventTab), QtGui.QApplication.translate("MainWindow", "Stats by Event Type", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMenu_Item.setText(QtGui.QApplication.translate("MainWindow", "Menu Item", None, QtGui.QApplication.UnicodeUTF8))

