# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/Filters.ui'
#
# Created: Fri Nov 21 09:38:52 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Filters(object):
    def setupUi(self, Filters):
        Filters.setObjectName("Filters")
        Filters.resize(435, 588)
        self.verticalLayout = QtGui.QVBoxLayout(Filters)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formatFrame = QtGui.QFrame(Filters)
        self.formatFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.formatFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.formatFrame.setObjectName("formatFrame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.formatFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formatLabel = QtGui.QLabel(self.formatFrame)
        self.formatLabel.setObjectName("formatLabel")
        self.verticalLayout_2.addWidget(self.formatLabel)
        self.formatListWidget = QtGui.QListWidget(self.formatFrame)
        self.formatListWidget.setObjectName("formatListWidget")
        self.verticalLayout_2.addWidget(self.formatListWidget)
        self.verticalLayout.addWidget(self.formatFrame)
        self.eventFrame = QtGui.QFrame(Filters)
        self.eventFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.eventFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.eventFrame.setObjectName("eventFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.eventFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.eventLabel = QtGui.QLabel(self.eventFrame)
        self.eventLabel.setObjectName("eventLabel")
        self.verticalLayout_3.addWidget(self.eventLabel)
        self.eventListWidget = QtGui.QListWidget(self.eventFrame)
        self.eventListWidget.setObjectName("eventListWidget")
        self.verticalLayout_3.addWidget(self.eventListWidget)
        self.verticalLayout.addWidget(self.eventFrame)
        self.deckFrame = QtGui.QFrame(Filters)
        self.deckFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.deckFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.deckFrame.setObjectName("deckFrame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.deckFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.deckLabel = QtGui.QLabel(self.deckFrame)
        self.deckLabel.setObjectName("deckLabel")
        self.verticalLayout_4.addWidget(self.deckLabel)
        self.deckListWidget = QtGui.QListWidget(self.deckFrame)
        self.deckListWidget.setObjectName("deckListWidget")
        self.verticalLayout_4.addWidget(self.deckListWidget)
        self.verticalLayout.addWidget(self.deckFrame)
        self.startingFrame = QtGui.QFrame(Filters)
        self.startingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.startingFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.startingFrame.setObjectName("startingFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.startingFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.datesLabel = QtGui.QLabel(self.startingFrame)
        self.datesLabel.setObjectName("datesLabel")
        self.horizontalLayout_2.addWidget(self.datesLabel)
        self.startingButton = QtGui.QPushButton(self.startingFrame)
        self.startingButton.setObjectName("startingButton")
        self.horizontalLayout_2.addWidget(self.startingButton)
        self.verticalLayout.addWidget(self.startingFrame)
        self.endingFrame = QtGui.QFrame(Filters)
        self.endingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.endingFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.endingFrame.setObjectName("endingFrame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.endingFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.endingFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.endingButton = QtGui.QPushButton(self.endingFrame)
        self.endingButton.setObjectName("endingButton")
        self.horizontalLayout_3.addWidget(self.endingButton)
        self.verticalLayout.addWidget(self.endingFrame)
        self.buttonFrame = QtGui.QFrame(Filters)
        self.buttonFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.buttonFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.updateFiltersButton = QtGui.QPushButton(self.buttonFrame)
        self.updateFiltersButton.setObjectName("updateFiltersButton")
        self.horizontalLayout.addWidget(self.updateFiltersButton)
        self.cancelButton = QtGui.QPushButton(self.buttonFrame)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addWidget(self.buttonFrame)

        self.retranslateUi(Filters)
        QtCore.QMetaObject.connectSlotsByName(Filters)

    def retranslateUi(self, Filters):
        Filters.setWindowTitle(QtGui.QApplication.translate("Filters", "Qute Data Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.formatLabel.setText(QtGui.QApplication.translate("Filters", "<html><head/><body><p><span style=\" font-size:16pt;\">Formats:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.eventLabel.setText(QtGui.QApplication.translate("Filters", "<html><head/><body><p><span style=\" font-size:16pt;\">Event Types:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.deckLabel.setText(QtGui.QApplication.translate("Filters", "<html><head/><body><p><span style=\" font-size:16pt;\">Decks:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.datesLabel.setText(QtGui.QApplication.translate("Filters", "<html><head/><body><p><span style=\" font-size:16pt;\">Starting Date:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.startingButton.setText(QtGui.QApplication.translate("Filters", "1991-01-01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Filters", "<html><head/><body><p><span style=\" font-size:16pt;\">Ending Date:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.endingButton.setText(QtGui.QApplication.translate("Filters", "2015-12-31", None, QtGui.QApplication.UnicodeUTF8))
        self.updateFiltersButton.setText(QtGui.QApplication.translate("Filters", "Apply Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("Filters", "Done", None, QtGui.QApplication.UnicodeUTF8))

