# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/Filters.ui'
#
# Created: Mon Nov 17 14:40:31 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Filters(object):
    def setupUi(self, Filters):
        Filters.setObjectName("Filters")
        Filters.resize(744, 511)
        self.verticalLayout = QtGui.QVBoxLayout(Filters)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filtersFrame = QtGui.QFrame(Filters)
        self.filtersFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.filtersFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.filtersFrame.setObjectName("filtersFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.filtersFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formatFrame = QtGui.QFrame(self.filtersFrame)
        self.formatFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.formatFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.formatFrame.setObjectName("formatFrame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.formatFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formatLabel = QtGui.QLabel(self.formatFrame)
        self.formatLabel.setObjectName("formatLabel")
        self.verticalLayout_2.addWidget(self.formatLabel)
        self.standardFilter = QtGui.QCheckBox(self.formatFrame)
        self.standardFilter.setChecked(True)
        self.standardFilter.setObjectName("standardFilter")
        self.verticalLayout_2.addWidget(self.standardFilter)
        self.modernFilter = QtGui.QCheckBox(self.formatFrame)
        self.modernFilter.setChecked(True)
        self.modernFilter.setObjectName("modernFilter")
        self.verticalLayout_2.addWidget(self.modernFilter)
        self.legacyFilter = QtGui.QCheckBox(self.formatFrame)
        self.legacyFilter.setChecked(True)
        self.legacyFilter.setObjectName("legacyFilter")
        self.verticalLayout_2.addWidget(self.legacyFilter)
        self.vintageFilter = QtGui.QCheckBox(self.formatFrame)
        self.vintageFilter.setChecked(True)
        self.vintageFilter.setObjectName("vintageFilter")
        self.verticalLayout_2.addWidget(self.vintageFilter)
        self.boosterDraftFilter = QtGui.QCheckBox(self.formatFrame)
        self.boosterDraftFilter.setChecked(True)
        self.boosterDraftFilter.setObjectName("boosterDraftFilter")
        self.verticalLayout_2.addWidget(self.boosterDraftFilter)
        self.sealedFilter = QtGui.QCheckBox(self.formatFrame)
        self.sealedFilter.setChecked(True)
        self.sealedFilter.setObjectName("sealedFilter")
        self.verticalLayout_2.addWidget(self.sealedFilter)
        self.twoHGSealedFilter = QtGui.QCheckBox(self.formatFrame)
        self.twoHGSealedFilter.setChecked(True)
        self.twoHGSealedFilter.setObjectName("twoHGSealedFilter")
        self.verticalLayout_2.addWidget(self.twoHGSealedFilter)
        self.casualConFilter = QtGui.QCheckBox(self.formatFrame)
        self.casualConFilter.setChecked(True)
        self.casualConFilter.setObjectName("casualConFilter")
        self.verticalLayout_2.addWidget(self.casualConFilter)
        self.casualLimFilter = QtGui.QCheckBox(self.formatFrame)
        self.casualLimFilter.setChecked(True)
        self.casualLimFilter.setObjectName("casualLimFilter")
        self.verticalLayout_2.addWidget(self.casualLimFilter)
        self.otherFormatFilter = QtGui.QCheckBox(self.formatFrame)
        self.otherFormatFilter.setChecked(True)
        self.otherFormatFilter.setObjectName("otherFormatFilter")
        self.verticalLayout_2.addWidget(self.otherFormatFilter)
        self.horizontalLayout_2.addWidget(self.formatFrame)
        self.eventFrame = QtGui.QFrame(self.filtersFrame)
        self.eventFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.eventFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.eventFrame.setObjectName("eventFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.eventFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.eventLabel = QtGui.QLabel(self.eventFrame)
        self.eventLabel.setObjectName("eventLabel")
        self.verticalLayout_3.addWidget(self.eventLabel)
        self.premiumTournamentFilter = QtGui.QCheckBox(self.eventFrame)
        self.premiumTournamentFilter.setChecked(True)
        self.premiumTournamentFilter.setObjectName("premiumTournamentFilter")
        self.verticalLayout_3.addWidget(self.premiumTournamentFilter)
        self.grandPrixFilter = QtGui.QCheckBox(self.eventFrame)
        self.grandPrixFilter.setChecked(True)
        self.grandPrixFilter.setObjectName("grandPrixFilter")
        self.verticalLayout_3.addWidget(self.grandPrixFilter)
        self.proTourFilter = QtGui.QCheckBox(self.eventFrame)
        self.proTourFilter.setChecked(True)
        self.proTourFilter.setObjectName("proTourFilter")
        self.verticalLayout_3.addWidget(self.proTourFilter)
        self.PTQFilter = QtGui.QCheckBox(self.eventFrame)
        self.PTQFilter.setChecked(True)
        self.PTQFilter.setObjectName("PTQFilter")
        self.verticalLayout_3.addWidget(self.PTQFilter)
        self.gameDayFilter = QtGui.QCheckBox(self.eventFrame)
        self.gameDayFilter.setChecked(True)
        self.gameDayFilter.setObjectName("gameDayFilter")
        self.verticalLayout_3.addWidget(self.gameDayFilter)
        self.prereleaseFilter = QtGui.QCheckBox(self.eventFrame)
        self.prereleaseFilter.setChecked(True)
        self.prereleaseFilter.setObjectName("prereleaseFilter")
        self.verticalLayout_3.addWidget(self.prereleaseFilter)
        self.GPTFilter = QtGui.QCheckBox(self.eventFrame)
        self.GPTFilter.setChecked(True)
        self.GPTFilter.setObjectName("GPTFilter")
        self.verticalLayout_3.addWidget(self.GPTFilter)
        self.FNMFilter = QtGui.QCheckBox(self.eventFrame)
        self.FNMFilter.setChecked(True)
        self.FNMFilter.setObjectName("FNMFilter")
        self.verticalLayout_3.addWidget(self.FNMFilter)
        self.WMCQFilter = QtGui.QCheckBox(self.eventFrame)
        self.WMCQFilter.setChecked(True)
        self.WMCQFilter.setObjectName("WMCQFilter")
        self.verticalLayout_3.addWidget(self.WMCQFilter)
        self.otherEventFilter = QtGui.QCheckBox(self.eventFrame)
        self.otherEventFilter.setChecked(True)
        self.otherEventFilter.setObjectName("otherEventFilter")
        self.verticalLayout_3.addWidget(self.otherEventFilter)
        self.horizontalLayout_2.addWidget(self.eventFrame)
        self.datesFrame = QtGui.QFrame(self.filtersFrame)
        self.datesFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.datesFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.datesFrame.setObjectName("datesFrame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.datesFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.datesLabel = QtGui.QLabel(self.datesFrame)
        self.datesLabel.setObjectName("datesLabel")
        self.verticalLayout_4.addWidget(self.datesLabel)
        self.startingDate = QtGui.QCalendarWidget(self.datesFrame)
        self.startingDate.setSelectedDate(QtCore.QDate(1991, 1, 1))
        self.startingDate.setMinimumDate(QtCore.QDate(1991, 1, 1))
        self.startingDate.setObjectName("startingDate")
        self.verticalLayout_4.addWidget(self.startingDate)
        self.label_2 = QtGui.QLabel(self.datesFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.endingDate = QtGui.QCalendarWidget(self.datesFrame)
        self.endingDate.setSelectedDate(QtCore.QDate(2015, 12, 31))
        self.endingDate.setMinimumDate(QtCore.QDate(1991, 1, 1))
        self.endingDate.setObjectName("endingDate")
        self.verticalLayout_4.addWidget(self.endingDate)
        self.horizontalLayout_2.addWidget(self.datesFrame)
        self.verticalLayout.addWidget(self.filtersFrame)
        self.buttonFrame = QtGui.QFrame(Filters)
        self.buttonFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.buttonFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.updateFiltersButton = QtGui.QPushButton(self.buttonFrame)
        self.updateFiltersButton.setObjectName("updateFiltersButton")
        self.horizontalLayout.addWidget(self.updateFiltersButton)
        self.cancelButton = QtGui.QPushButton(self.buttonFrame)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addWidget(self.buttonFrame)

        self.retranslateUi(Filters)
        QtCore.QMetaObject.connectSlotsByName(Filters)

    def retranslateUi(self, Filters):
        Filters.setWindowTitle(QtGui.QApplication.translate("Filters", "Qute Data Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.formatLabel.setText(QtGui.QApplication.translate("Filters", "<html><head/><body><p><span style=\" font-size:16pt;\">Formats:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.standardFilter.setToolTip(QtGui.QApplication.translate("Filters", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.standardFilter.setText(QtGui.QApplication.translate("Filters", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.modernFilter.setToolTip(QtGui.QApplication.translate("Filters", "Modern", None, QtGui.QApplication.UnicodeUTF8))
        self.modernFilter.setText(QtGui.QApplication.translate("Filters", "Modern", None, QtGui.QApplication.UnicodeUTF8))
        self.legacyFilter.setToolTip(QtGui.QApplication.translate("Filters", "Legacy", None, QtGui.QApplication.UnicodeUTF8))
        self.legacyFilter.setText(QtGui.QApplication.translate("Filters", "Legacy", None, QtGui.QApplication.UnicodeUTF8))
        self.vintageFilter.setToolTip(QtGui.QApplication.translate("Filters", "Vintage", None, QtGui.QApplication.UnicodeUTF8))
        self.vintageFilter.setText(QtGui.QApplication.translate("Filters", "Vintage", None, QtGui.QApplication.UnicodeUTF8))
        self.boosterDraftFilter.setToolTip(QtGui.QApplication.translate("Filters", "Booster Draft", None, QtGui.QApplication.UnicodeUTF8))
        self.boosterDraftFilter.setText(QtGui.QApplication.translate("Filters", "Booster Draft", None, QtGui.QApplication.UnicodeUTF8))
        self.sealedFilter.setToolTip(QtGui.QApplication.translate("Filters", "Sealed", None, QtGui.QApplication.UnicodeUTF8))
        self.sealedFilter.setText(QtGui.QApplication.translate("Filters", "Sealed", None, QtGui.QApplication.UnicodeUTF8))
        self.twoHGSealedFilter.setToolTip(QtGui.QApplication.translate("Filters", "2 HG Sealed", None, QtGui.QApplication.UnicodeUTF8))
        self.twoHGSealedFilter.setText(QtGui.QApplication.translate("Filters", "2 HG Sealed", None, QtGui.QApplication.UnicodeUTF8))
        self.casualConFilter.setToolTip(QtGui.QApplication.translate("Filters", "Casual - Constructed", None, QtGui.QApplication.UnicodeUTF8))
        self.casualConFilter.setText(QtGui.QApplication.translate("Filters", "Casual - Con", None, QtGui.QApplication.UnicodeUTF8))
        self.casualLimFilter.setToolTip(QtGui.QApplication.translate("Filters", "Casual - Limited", None, QtGui.QApplication.UnicodeUTF8))
        self.casualLimFilter.setText(QtGui.QApplication.translate("Filters", "Casual - Lim", None, QtGui.QApplication.UnicodeUTF8))
        self.otherFormatFilter.setToolTip(QtGui.QApplication.translate("Filters", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.otherFormatFilter.setText(QtGui.QApplication.translate("Filters", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.eventLabel.setText(QtGui.QApplication.translate("Filters", "<html><head/><body><p><span style=\" font-size:16pt;\">Event Types:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.premiumTournamentFilter.setToolTip(QtGui.QApplication.translate("Filters", "Magic WPN Premium Tournament", None, QtGui.QApplication.UnicodeUTF8))
        self.premiumTournamentFilter.setText(QtGui.QApplication.translate("Filters", "Premium Tournament", None, QtGui.QApplication.UnicodeUTF8))
        self.grandPrixFilter.setToolTip(QtGui.QApplication.translate("Filters", "Magic Grand Prix", None, QtGui.QApplication.UnicodeUTF8))
        self.grandPrixFilter.setText(QtGui.QApplication.translate("Filters", "Grand Prix", None, QtGui.QApplication.UnicodeUTF8))
        self.proTourFilter.setToolTip(QtGui.QApplication.translate("Filters", "Magic Pro Tour", None, QtGui.QApplication.UnicodeUTF8))
        self.proTourFilter.setText(QtGui.QApplication.translate("Filters", "Pro Tour", None, QtGui.QApplication.UnicodeUTF8))
        self.PTQFilter.setToolTip(QtGui.QApplication.translate("Filters", "Magic Pro Tour Qualifier", None, QtGui.QApplication.UnicodeUTF8))
        self.PTQFilter.setText(QtGui.QApplication.translate("Filters", "Pro Tour Qualifier", None, QtGui.QApplication.UnicodeUTF8))
        self.gameDayFilter.setToolTip(QtGui.QApplication.translate("Filters", "Magic Game Day", None, QtGui.QApplication.UnicodeUTF8))
        self.gameDayFilter.setText(QtGui.QApplication.translate("Filters", "Game Day", None, QtGui.QApplication.UnicodeUTF8))
        self.prereleaseFilter.setToolTip(QtGui.QApplication.translate("Filters", "Magic Prerelease", None, QtGui.QApplication.UnicodeUTF8))
        self.prereleaseFilter.setText(QtGui.QApplication.translate("Filters", "Prerelease", None, QtGui.QApplication.UnicodeUTF8))
        self.GPTFilter.setToolTip(QtGui.QApplication.translate("Filters", "Magic Grand Prix Trial", None, QtGui.QApplication.UnicodeUTF8))
        self.GPTFilter.setText(QtGui.QApplication.translate("Filters", "Grand Prix Trial", None, QtGui.QApplication.UnicodeUTF8))
        self.FNMFilter.setToolTip(QtGui.QApplication.translate("Filters", "Friday Night Magic", None, QtGui.QApplication.UnicodeUTF8))
        self.FNMFilter.setText(QtGui.QApplication.translate("Filters", "Friday Night Magic", None, QtGui.QApplication.UnicodeUTF8))
        self.WMCQFilter.setToolTip(QtGui.QApplication.translate("Filters", "World Magic Cup Qualifier", None, QtGui.QApplication.UnicodeUTF8))
        self.WMCQFilter.setText(QtGui.QApplication.translate("Filters", "WMCQ", None, QtGui.QApplication.UnicodeUTF8))
        self.otherEventFilter.setToolTip(QtGui.QApplication.translate("Filters", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.otherEventFilter.setText(QtGui.QApplication.translate("Filters", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.datesLabel.setText(QtGui.QApplication.translate("Filters", "<html><head/><body><p><span style=\" font-size:16pt;\">Starting Date:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Filters", "<html><head/><body><p><span style=\" font-size:16pt;\">Ending Date:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.updateFiltersButton.setText(QtGui.QApplication.translate("Filters", "Apply Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("Filters", "Done", None, QtGui.QApplication.UnicodeUTF8))

