# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/Main.ui'
#
# Created: Sun Nov 16 22:11:41 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(438, 391)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.setupFrame = QtGui.QFrame(self.centralwidget)
        self.setupFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.setupFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.setupFrame.setObjectName("setupFrame")
        self.verticalLayout = QtGui.QVBoxLayout(self.setupFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.setupLabelFrame = QtGui.QFrame(self.setupFrame)
        self.setupLabelFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.setupLabelFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.setupLabelFrame.setObjectName("setupLabelFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.setupLabelFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setupLabel = QtGui.QLabel(self.setupLabelFrame)
        self.setupLabel.setObjectName("setupLabel")
        self.horizontalLayout_2.addWidget(self.setupLabel)
        self.dataLoadedLabel = QtGui.QLabel(self.setupLabelFrame)
        self.dataLoadedLabel.setObjectName("dataLoadedLabel")
        self.horizontalLayout_2.addWidget(self.dataLoadedLabel)
        self.verticalLayout.addWidget(self.setupLabelFrame)
        self.setupButtonFrame = QtGui.QFrame(self.setupFrame)
        self.setupButtonFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.setupButtonFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.setupButtonFrame.setObjectName("setupButtonFrame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.setupButtonFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadFromFileButton = QtGui.QPushButton(self.setupButtonFrame)
        self.loadFromFileButton.setObjectName("loadFromFileButton")
        self.horizontalLayout.addWidget(self.loadFromFileButton)
        self.pasteDataFromSiteButton = QtGui.QPushButton(self.setupButtonFrame)
        self.pasteDataFromSiteButton.setObjectName("pasteDataFromSiteButton")
        self.horizontalLayout.addWidget(self.pasteDataFromSiteButton)
        self.adjustFiltersButton = QtGui.QPushButton(self.setupButtonFrame)
        self.adjustFiltersButton.setEnabled(False)
        self.adjustFiltersButton.setObjectName("adjustFiltersButton")
        self.horizontalLayout.addWidget(self.adjustFiltersButton)
        self.verticalLayout.addWidget(self.setupButtonFrame)
        self.verticalLayout_4.addWidget(self.setupFrame)
        self.statsFrame = QtGui.QFrame(self.centralwidget)
        self.statsFrame.setEnabled(False)
        self.statsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.statsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.statsFrame.setObjectName("statsFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.statsFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.statsLabel = QtGui.QLabel(self.statsFrame)
        self.statsLabel.setObjectName("statsLabel")
        self.verticalLayout_3.addWidget(self.statsLabel)
        self.statsButtonFrame = QtGui.QFrame(self.statsFrame)
        self.statsButtonFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.statsButtonFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.statsButtonFrame.setObjectName("statsButtonFrame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.statsButtonFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.byFormatButton = QtGui.QPushButton(self.statsButtonFrame)
        self.byFormatButton.setObjectName("byFormatButton")
        self.horizontalLayout_4.addWidget(self.byFormatButton)
        self.byEventButton = QtGui.QPushButton(self.statsButtonFrame)
        self.byEventButton.setObjectName("byEventButton")
        self.horizontalLayout_4.addWidget(self.byEventButton)
        self.byDeckButton = QtGui.QPushButton(self.statsButtonFrame)
        self.byDeckButton.setObjectName("byDeckButton")
        self.horizontalLayout_4.addWidget(self.byDeckButton)
        self.verticalLayout_3.addWidget(self.statsButtonFrame)
        self.verticalLayout_4.addWidget(self.statsFrame)
        self.listFrame = QtGui.QFrame(self.centralwidget)
        self.listFrame.setEnabled(False)
        self.listFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.listFrame.setObjectName("listFrame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.listFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listLabel = QtGui.QLabel(self.listFrame)
        self.listLabel.setObjectName("listLabel")
        self.verticalLayout_2.addWidget(self.listLabel)
        self.listButtonFrame = QtGui.QFrame(self.listFrame)
        self.listButtonFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listButtonFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.listButtonFrame.setObjectName("listButtonFrame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.listButtonFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listEventButton = QtGui.QPushButton(self.listButtonFrame)
        self.listEventButton.setObjectName("listEventButton")
        self.horizontalLayout_3.addWidget(self.listEventButton)
        self.listOpponentButton = QtGui.QPushButton(self.listButtonFrame)
        self.listOpponentButton.setObjectName("listOpponentButton")
        self.horizontalLayout_3.addWidget(self.listOpponentButton)
        self.verticalLayout_2.addWidget(self.listButtonFrame)
        self.verticalLayout_4.addWidget(self.listFrame)
        self.saveDataButton = QtGui.QPushButton(self.centralwidget)
        self.saveDataButton.setEnabled(False)
        self.saveDataButton.setObjectName("saveDataButton")
        self.verticalLayout_4.addWidget(self.saveDataButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Qute MTG Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.setupLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Setup</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.dataLoadedLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-style:italic;\">No Data Loaded</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFromFileButton.setText(QtGui.QApplication.translate("MainWindow", "Load Data from File", None, QtGui.QApplication.UnicodeUTF8))
        self.pasteDataFromSiteButton.setText(QtGui.QApplication.translate("MainWindow", "Paste Data from Website", None, QtGui.QApplication.UnicodeUTF8))
        self.adjustFiltersButton.setText(QtGui.QApplication.translate("MainWindow", "Adjust Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.statsLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Stats By</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.byFormatButton.setText(QtGui.QApplication.translate("MainWindow", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.byEventButton.setText(QtGui.QApplication.translate("MainWindow", "Event Type", None, QtGui.QApplication.UnicodeUTF8))
        self.byDeckButton.setText(QtGui.QApplication.translate("MainWindow", "Deck", None, QtGui.QApplication.UnicodeUTF8))
        self.listLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">List Of</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.listEventButton.setText(QtGui.QApplication.translate("MainWindow", "Events", None, QtGui.QApplication.UnicodeUTF8))
        self.listOpponentButton.setText(QtGui.QApplication.translate("MainWindow", "Opponents", None, QtGui.QApplication.UnicodeUTF8))
        self.saveDataButton.setText(QtGui.QApplication.translate("MainWindow", "Save Data to File", None, QtGui.QApplication.UnicodeUTF8))

